# Steps that happen regardless of CI, PR, or release builds
steps:
  - task: NodeTool@0
    displayName: 'Use Node 9.x'
    inputs:
      versionSpec: 9.x

  - script: |
      sudo cp .azure-pipelines/linux/xvfb.init /etc/init.d/xvfb
      sudo chmod +x /etc/init.d/xvfb
      sudo update-rc.d xvfb defaults
      sudo service xvfb start
    displayName: 'Linux: Start X Virtual Frame Buffer'
    condition: eq(variables['Agent.OS'], 'Linux')

  - script: yarn install --frozen-lockfile
    displayName: yarn install

  - script: 'node node_modules/gulp/bin/gulp.js package'
    displayName: 'gulp package'
    env:
      DISPLAY: :10

  - task: CopyFiles@2
    displayName: Stage VSIX for publishing
    condition: eq(variables['Agent.OS'], 'Linux')
    inputs:
      contents: |-
        *.vsix
        version.txt
      targetFolder: $(Build.ArtifactStagingDirectory)

  - task: PublishBuildArtifacts@1
    displayName: Publish VSIX
    condition: eq(variables['Agent.OS'], 'Linux')
    inputs:
      pathToPublish: $(Build.ArtifactStagingDirectory)
      artifactName: vrealize-developer-tools
