name: Publish Release
on:
  release:
    types: [released]
jobs:
  publish:
    name: Publish to Visual Studio Marketplace and GitHub Packages
    runs-on: ubuntu-latest
    steps:
      - name: Use Node.js 12.x
        uses: actions/setup-node@v2
        with:
          node-version: 12.x

      - name: Install vsce
        run: npm install -g vsce

      - name: Import GPG key
        id: import_gpg
        uses: crazy-max/ghaction-import-gpg@v2
        env:
          GPG_PRIVATE_KEY: ${{ secrets.RELEASE_GPG_PRIVATE_KEY }}
          PASSPHRASE: ${{ secrets.RELEASE_GPG_PASSPHRASE }}

      - name: Download release assets
        id: release_asset
        env:
          TAG_NAME: ${{ github.event.release.tag_name }}
        run: gh release download $TAG_NAME

      - name: Verify all release assets
        env:
          TAG_NAME: ${{ github.event.release.tag_name }}
          KEYID: ${{steps.import_gpg.outputs.keyid}}
        run: |
          gpg --keyid-format long --verify vrealize-developer-tools-${TAG_NAME#v}.vsix.sha256.asc vrealize-developer-tools-${TAG_NAME#v}.vsix.sha256
          gpg --keyid-format long --verify packages.sha256.asc packages.sha256

          sha256sum -c vrealize-developer-tools-${TAG_NAME#v}.vsix.sha256
          sha256sum -c packages.sha256

      - name: Publish extension to VS Marketplace
        env:
          TAG_NAME: ${{ github.event.release.tag_name }}
          MARKETPLACE_SECRET: ${{ secrets.VS_MARKETPLACE_TOKEN }}
        run: "vsce publish -p $MARKETPLACE_SECRET --packagePath vrealize-developer-tools-${TAG_NAME#v}.vsix"

      - name: Publish npm packages to GitHub Packages Registry
        env:
          TAG_NAME: ${{ github.event.release.tag_name }}
          NODE_AUTH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: | # uses the package.json's publishConfig/registry URL
          find *.tgz -type f -exec npm publish {} \;
