name: Publish Release
on:
  release:
    types: [released]
jobs:
  publish:
    name: Publish to Visual Studio Marketplace and GitHub Packages
    runs-on: ubuntu-latest
    steps:
      - name: Use Node.js 19.6.0
        uses: actions/setup-node@v2
        with:
          node-version: 19.6.0

      - name: Install vsce
        run: npm install -g vsce

      - name: Download release assets
        id: release_asset
        env:
          TAG_NAME: ${{ github.event.release.tag_name }}
          GITHUB_TOKEN: ${{secrets.GITHUB_TOKEN}}
        run: gh release download $TAG_NAME -R vmware/vrealize-developer-tools

      - name: Verify checksum signatures
        run: |
          /bin/bash -c "$(curl -fsSL https://raw.githubusercontent.com/Homebrew/install/HEAD/install.sh)"
          (echo; echo 'eval "$(/home/linuxbrew/.linuxbrew/bin/brew shellenv)"') >> /home/runner/.bashrc
          eval "$(/home/linuxbrew/.linuxbrew/bin/brew shellenv)"
          brew update
          brew install coreutils minisign

          minisign -Vm vrealize-developer-tools-${TAG_NAME#v}.vsix.sha256 -P "RWSLXIQU0b52vHvyFK7d0SQmt3he8hrZnBzwp/e30XALf4rtRc0Cluhh"
          minisign -Vm packages.sha256 -P "RWSLXIQU0b52vHvyFK7d0SQmt3he8hrZnBzwp/e30XALf4rtRc0Cluhh"
        env:
          TAG_NAME: ${{ github.event.release.tag_name }}

      - name: Verify checksums of all release assets
        env:
          TAG_NAME: ${{ github.event.release.tag_name }}
        run: |
          sha256sum -c vrealize-developer-tools-${TAG_NAME#v}.vsix.sha256
          sha256sum -c packages.sha256

      - name: Publish extension to VS Marketplace
        env:
          TAG_NAME: ${{ github.event.release.tag_name }}
          MARKETPLACE_SECRET: ${{ secrets.VS_MARKETPLACE_TOKEN }}
        run: "vsce publish -p $MARKETPLACE_SECRET --packagePath vrealize-developer-tools-${TAG_NAME#v}.vsix"

      - name: Publish npm packages to GitHub Packages Registry
        env:
          TAG_NAME: ${{ github.event.release.tag_name }}
          NODE_AUTH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: | # uses the package.json's publishConfig/registry URL
          find *.tgz -type f -exec npm publish {} \;
