name: Publish Release
on:
  release:
    types: [released]
jobs:
  publish:
    name: Publish to Visual Studio Marketplace and GitHub Packages
    runs-on: ubuntu-latest
    steps:
      - name: Use Node.js 16.x
        uses: actions/setup-node@v2
        with:
          node-version: 16.x

      - name: Install vsce
        run: npm install -g vsce

      - name: Download release assets
        id: release_asset
        env:
          TAG_NAME: ${{ github.event.release.tag_name }}
        run: gh release download $TAG_NAME

      - name: Verify VSIX signature
        uses: thomaso-mirodin/minisign-action@v1.1
        with:
          args: -Vm vrealize-developer-tools-${TAG_NAME#v}.vsix.sha256 -P "RWSLXIQU0b52vHvyFK7d0SQmt3he8hrZnBzwp/e30XALf4rtRc0Cluhh"
          minisign_key: ${{ secrets.RELEASE_MINISIGN_KEY }}
          password: ${{ secrets.RELEASE_MINISIGN_PASS }}

      - name: Verify packages signature
        uses: thomaso-mirodin/minisign-action@v1.1
        with:
          args: -Vm packages.sha256 -P "RWSLXIQU0b52vHvyFK7d0SQmt3he8hrZnBzwp/e30XALf4rtRc0Cluhh"
          minisign_key: ${{ secrets.RELEASE_MINISIGN_KEY }}
          password: ${{ secrets.RELEASE_MINISIGN_PASS }}

      - name: Verify checksums of all release assets
        env:
          TAG_NAME: ${{ github.event.release.tag_name }}
        run: |
          sha256sum -c vrealize-developer-tools-${TAG_NAME#v}.vsix.sha256
          sha256sum -c packages.sha256

      - name: Publish extension to VS Marketplace
        env:
          TAG_NAME: ${{ github.event.release.tag_name }}
          MARKETPLACE_SECRET: ${{ secrets.VS_MARKETPLACE_TOKEN }}
        run: "vsce publish -p $MARKETPLACE_SECRET --packagePath vrealize-developer-tools-${TAG_NAME#v}.vsix"

      - name: Publish npm packages to GitHub Packages Registry
        env:
          TAG_NAME: ${{ github.event.release.tag_name }}
          NODE_AUTH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: | # uses the package.json's publishConfig/registry URL
          find *.tgz -type f -exec npm publish {} \;
